# syntax=docker/dockerfile:1
FROM python:3
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED=1
WORKDIR /code/
COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY . /code/
RUN python /code/manage.py collectstatic --noinput --clear
RUN chmod -R 755 /code/static/
RUN chown -R "$USER":www-data /code/
EXPOSE 8000
