version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: 'Dockerfile'
    command: >
      bash -c "./entrypoint.prod.sh
      && python manage.py makemigrations
      && python manage.py migrate
      && python manage.py initadmin
      && gunicorn uteoj.wsgi:application --timeout=1000 --bind 0.0.0.0:8000
      "
    volumes:
      - ./webdata/media:/code/judge_data/
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - '3309:3309'
    environment:
       MYSQL_DATABASE: 'uteoj'
       MYSQL_ROOT_PASSWORD: 'hcmute.f18c1a3b9e1b16e36d26fc6420ac985d'
    volumes:
      - ./webdata/db:/var/lib/mysql
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - ./static:/code/static/
    depends_on:
      - web
volumes:
  postgres_data:
  production_db_volume:
