version: '3.7'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: 'Dockerfile'
    command: >
      bash -c "./entrypoint.prod.sh
      && python manage.py makemigrations
      && python manage.py migrate
      && python manage.py initadmin
      && python manage.py grader --reset
      && gunicorn uteoj.wsgi:application --timeout=1000 --bind 0.0.0.0:8000
      "
    volumes:
      - ./webdata/media:/uteoj_data/
      - static_volume:/code/static
      - libjudger:/code/libjudger
    expose:
      - 8000
    depends_on:
      - db
  db:
    restart: always
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - '3309:3309'
    environment:
       MYSQL_DATABASE: 'uteoj'
       MYSQL_ROOT_PASSWORD: 'hcmute.f18c1a3b9e1b16e36d26fc6420ac985d'
    volumes:
      - ./webdata/db:/var/lib/mysql
  redis:
    restart: always
    image: redis:alpine
  nginx:
    restart: always
    build: ./nginx
    ports:
      - 8000:80
    volumes:
      - static_volume:/code/static
    depends_on:
      - web
  celery:
    restart: always
    build:
      context: .
    command: >
      bash -c "celery -A uteoj worker -Q uteoj_judger -Ofair
      & celery -A uteoj worker -Q uteoj_system -Ofair
      "
    volumes:
      - ./webdata/media:/uteoj_data/
      - libjudger:/usr/lib/judger
    depends_on:
      - db
      - redis
      - web
      
volumes:
  static_volume:
  problem_volume:
  libjudger:

