# Generated by Django 3.2 on 2021-06-29 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('ext', models.CharField(max_length=6)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProblemCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('shortname', models.CharField(max_length=32)),
                ('fullname', models.CharField(max_length=255)),
                ('difficult', models.FloatField(default=5.0)),
                ('points_per_test', models.FloatField(default=1.0)),
                ('statement', models.TextField()),
                ('input_filename', models.CharField(max_length=32)),
                ('output_filename', models.CharField(max_length=32)),
                ('use_stdin', models.BooleanField(default=True)),
                ('use_stdout', models.BooleanField(default=True)),
                ('time_limit', models.IntegerField(default=1000)),
                ('memory_limit', models.IntegerField(default=65536)),
                ('checker', models.CharField(blank=True, max_length=64)),
                ('problem_type', models.IntegerField(choices=[(0, 'ACM'), (1, 'OI')], default=0)),
                ('author', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, to='backend.ProblemCategoryModel')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('submission_judge_date', models.DateTimeField(blank=True)),
                ('compile_message', models.TextField(blank=True)),
                ('executed_time', models.IntegerField(blank=True)),
                ('memory_usage', models.IntegerField(blank=True)),
                ('points', models.FloatField(blank=True)),
                ('result', models.IntegerField(blank=True, choices=[(-1, 'Compile error'), (0, 'Accept'), (1, 'Wrong answer'), (2, 'Time limit exceeded'), (3, 'memory limit exceeded'), (4, 'Runtime error'), (5, 'Output Limit Exceed'), (6, 'Presentation Error')])),
                ('status', models.IntegerField(blank=True, choices=[(0, 'In queued'), (1, 'Compiling'), (2, 'Grading'), (3, 'Completed')])),
                ('lastest_test', models.IntegerField(default=-1)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.languagemodel')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.problemmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionTestcaseResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_time', models.IntegerField()),
                ('memory_usage', models.IntegerField()),
                ('points', models.FloatField()),
                ('checker_message', models.TextField(blank=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.submissionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemTestCaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_limit', models.IntegerField(default=1000)),
                ('memory_limit', models.IntegerField(default=65536)),
                ('points', models.FloatField(default=1.0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.problemmodel')),
            ],
        ),
    ]
