# Generated by Django 3.2 on 2021-06-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemmodel',
            name='shortname',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
