# Generated by Django 3.2 on 2021-06-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_problemmodel_shortname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemcategorymodel',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
