# Generated by Django 3.2 on 2021-09-27 09:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210927_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestmodel',
            name='endTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contestmodel',
            name='startTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='problemmodel',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 27, 9, 47, 29, 42731, tzinfo=utc)),
        ),
    ]
