# Generated by Django 3.2 on 2021-08-31 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_submissionmodel_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemstatisticsmodel',
            name='acceptCount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='problemstatisticsmodel',
            name='submitCount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
