# Generated by Django 3.2 on 2021-09-28 04:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210927_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemtestcasemodel',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.contestmodel'),
        ),
        migrations.AlterField(
            model_name='problemmodel',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 28, 4, 42, 39, 673595, tzinfo=utc)),
        ),
    ]
