# Generated by Django 3.2 on 2021-08-31 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210831_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemstatisticsmodel',
            name='acceptCount',
        ),
    ]
