# Generated by Django 3.2 on 2021-06-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_problemcategorymodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagemodel',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
