# Generated by Django 3.2 on 2021-09-28 04:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210928_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemtestcasemodel',
            name='contest',
        ),
        migrations.AlterField(
            model_name='problemmodel',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 28, 4, 47, 37, 162475, tzinfo=utc)),
        ),
    ]
