# Generated by Django 3.2 on 2021-06-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_languagemodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionmodel',
            name='result',
            field=models.IntegerField(choices=[(-2, 'None'), (-1, 'Compile error'), (0, 'Accept'), (1, 'Wrong answer'), (2, 'Time limit exceeded'), (3, 'memory limit exceeded'), (4, 'Runtime error'), (5, 'Output Limit Exceed'), (6, 'Presentation Error')], default=-2),
        ),
        migrations.AlterField(
            model_name='submissionmodel',
            name='status',
            field=models.IntegerField(choices=[(-1, 'None'), (0, 'In queued'), (1, 'Compiling'), (2, 'Grading'), (3, 'Completed')], default=-1),
        ),
    ]
