# Generated by Django 3.2 on 2021-09-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_userstatisticsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatisticsmodel',
            name='mleCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatisticsmodel',
            name='rteCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatisticsmodel',
            name='tleCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatisticsmodel',
            name='totalSubmission',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatisticsmodel',
            name='waCount',
            field=models.IntegerField(default=0),
        ),
    ]
