# Generated by Django 3.2 on 2021-06-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210629_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionmodel',
            name='compile_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissionmodel',
            name='executed_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissionmodel',
            name='memory_usage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissionmodel',
            name='result',
            field=models.IntegerField(blank=True, choices=[(-2, 'None'), (-1, 'Compile error'), (0, 'Accept'), (1, 'Wrong answer'), (2, 'Time limit exceeded'), (3, 'memory limit exceeded'), (4, 'Runtime error'), (5, 'Output Limit Exceed'), (6, 'Presentation Error')], null=True),
        ),
        migrations.AlterField(
            model_name='submissionmodel',
            name='status',
            field=models.IntegerField(blank=True, choices=[(-1, 'None'), (0, 'In queued'), (1, 'Compiling'), (2, 'Grading'), (3, 'Completed')], null=True),
        ),
        migrations.AlterField(
            model_name='submissionmodel',
            name='submission_judge_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
