# Generated by Django 3.2 on 2021-09-04 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0006_auto_20210903_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProblemStatisticsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalSubmission', models.IntegerField(default=0)),
                ('solvedCount', models.IntegerField(default=0)),
                ('waCount', models.IntegerField(default=0)),
                ('tleCount', models.IntegerField(default=0)),
                ('rteCount', models.IntegerField(default=0)),
                ('mleCount', models.IntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.problemmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'problem')},
            },
        ),
        migrations.DeleteModel(
            name='UserStatisticsModel',
        ),
    ]
