# Generated by Django 3.2 on 2021-06-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210629_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionmodel',
            name='submission_date',
            field=models.DateTimeField(),
        ),
    ]
