# Generated by Django 3.2 on 2021-09-28 09:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_problemmodel_publish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestmodel',
            name='problems',
        ),
        migrations.AddField(
            model_name='problemmodel',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.contestmodel'),
        ),
        migrations.AlterField(
            model_name='problemmodel',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 28, 9, 23, 12, 155222, tzinfo=utc)),
        ),
    ]
