# Generated by Django 3.2 on 2021-09-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210904_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemstatisticsmodel',
            name='ceCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userproblemstatisticsmodel',
            name='ceCount',
            field=models.IntegerField(default=0),
        ),
    ]
