# Generated by Django 3.2 on 2021-07-02 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_problemmodel_publish_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OJSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='problemtestcasemodel',
            name='test_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ProblemStatisticsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solvedCount', models.IntegerField(default=0)),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.problemmodel')),
            ],
        ),
    ]
