# Generated by Django 3.2 on 2021-09-28 16:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210928_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemmodel',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 28, 16, 27, 51, 227971, tzinfo=utc)),
        ),
    ]
