# Generated by Django 3.2 on 2021-07-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20210702_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemmodel',
            name='submission_visible_mode',
            field=models.IntegerField(choices=[(0, 'Ai cũng có thể xem được'), (1, 'Chỉ những người giải được'), (2, 'Chỉ mình tôi')], default=0),
        ),
    ]
