# Generated by Django 3.2 on 2021-09-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_submissiontestcaseresultmodel_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagemodel',
            name='execute_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
