# Generated by Django 3.2 on 2021-07-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_problemmodel_submission_visible_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemcategorymodel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
