# Generated by Django 3.2 on 2021-09-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_languagemodel_execute_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagemodel',
            name='ext',
            field=models.CharField(max_length=128),
        ),
    ]
