# Generated by Django 3.2 on 2021-07-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_problemcategorymodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemcategorymodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
