# Generated by Django 3.2 on 2021-10-04 08:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20211002_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemmodel',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 4, 8, 11, 24, 41183, tzinfo=utc)),
        ),
    ]
