# Generated by Django 3.2 on 2021-09-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_languagemodel_ext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagemodel',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
