# Generated by Django 3.2 on 2021-09-12 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0013_alter_languagemodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproblemstatisticsmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userproblemstatisticsmodel',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userproblemstatisticsmodel',
            name='problem',
        ),
    ]
