# Generated by Django 3.2 on 2021-09-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20210912_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionmodel',
            name='points',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
