# Generated by Django 3.2 on 2021-07-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20210712_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagemodel',
            name='compile_command',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='languagemodel',
            name='run_command',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
