# Generated by Django 3.2 on 2021-09-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_submissionmodel_lastest_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemsettingmodel',
            name='total_points',
            field=models.FloatField(default=0.0),
        ),
    ]
