# Generated by Django 3.2 on 2021-07-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20210713_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagemodel',
            name='ext',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
