# Generated by Django 3.2 on 2021-07-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_languagemodel_ext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagemodel',
            name='ext',
            field=models.CharField(max_length=6),
        ),
    ]
