# Generated by Django 3.2 on 2021-09-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_problemsettingmodel_total_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemsettingmodel',
            name='total_points',
        ),
        migrations.AddField(
            model_name='languagemodel',
            name='class_name',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
