# Generated by Django 3.2 on 2021-09-13 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20210913_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontestcaseresultmodel',
            name='testcase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.problemtestcasemodel'),
        ),
    ]
