# Generated by Django 3.2 on 2021-07-14 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_languagemodel_ext'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemmodel',
            name='constraints_statement',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='problemmodel',
            name='input_statement',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='problemmodel',
            name='output_statement',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='problemmodel',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 22, 55, 58, 39925)),
        ),
    ]
