# Generated by Django 3.2 on 2021-09-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_submissiontestcaseresultmodel_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemtestcasemodel',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
