# Generated by Django 3.2 on 2021-09-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_problemtestcasemodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemsettingmodel',
            name='total_points',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
