# Generated by Django 3.2 on 2021-07-15 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_problemmodel_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemtestcasemodel',
            name='input_file',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='problemtestcasemodel',
            name='output_file',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='problemmodel',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 19, 25, 43, 893678)),
        ),
    ]
