# Generated by Django 3.2 on 2021-07-15 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20210715_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemmodel',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 19, 27, 21, 233030)),
        ),
        migrations.AlterField(
            model_name='problemtestcasemodel',
            name='test_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
