# Generated by Django 3.2 on 2021-07-15 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_auto_20210715_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemtestcasemodel',
            old_name='test_name',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='problemmodel',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 22, 41, 13, 339827)),
        ),
    ]
