# Generated by Django 3.2 on 2021-07-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_alter_problemmodel_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemmodel',
            name='categories_str',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
