# Generated by Django 3.2 on 2021-07-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_auto_20210722_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='hash_user_profile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='UserFileManager',
        ),
    ]
