# Generated by Django 3.2 on 2021-07-24 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_auto_20210723_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemmodel',
            name='categories_str',
        ),
        migrations.RemoveField(
            model_name='problemmodel',
            name='checker',
        ),
        migrations.RemoveField(
            model_name='problemmodel',
            name='constraints_statement',
        ),
        migrations.RemoveField(
            model_name='problemmodel',
            name='input_filename',
        ),
        migrations.RemoveField(
            model_name='problemmodel',
            name='input_statement',
        ),
        migrations.RemoveField(
            model_name='problemmodel',
            name='memory_limit',
        ),
        migrations.RemoveField(
            model_name='problemmodel',
            name='output_filename',
        ),
        migrations.RemoveField(
            model_name='problemmodel',
            name='output_statement',
        ),
        migrations.RemoveField(
            model_name='problemmodel',
            name='points_per_test',
        ),
        migrations.RemoveField(
            model_name='problemmodel',
            name='statement',
        ),
        migrations.RemoveField(
            model_name='problemmodel',
            name='submission_visible_mode',
        ),
        migrations.RemoveField(
            model_name='problemmodel',
            name='time_limit',
        ),
        migrations.RemoveField(
            model_name='problemmodel',
            name='use_checker',
        ),
        migrations.RemoveField(
            model_name='problemmodel',
            name='use_stdin',
        ),
        migrations.RemoveField(
            model_name='problemmodel',
            name='use_stdout',
        ),
        migrations.AddField(
            model_name='problemmodel',
            name='hash_problem',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='ProblemSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_test', models.FloatField(default=1.0)),
                ('statement', models.TextField()),
                ('input_statement', models.TextField(null=True)),
                ('output_statement', models.TextField(null=True)),
                ('constraints_statement', models.TextField(null=True)),
                ('submission_visible_mode', models.IntegerField(choices=[(0, 'Ai cũng có thể xem được'), (1, 'Chỉ những người giải được'), (2, 'Chỉ mình tôi')], default=0)),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.problemmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemGraderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_filename', models.CharField(max_length=32)),
                ('output_filename', models.CharField(max_length=32)),
                ('use_stdin', models.BooleanField(default=True)),
                ('use_stdout', models.BooleanField(default=True)),
                ('time_limit', models.IntegerField(default=1000)),
                ('memory_limit', models.IntegerField(default=65536)),
                ('use_checker', models.BooleanField(default=False)),
                ('checker', models.TextField(blank=True, default='')),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.problemmodel')),
            ],
        ),
    ]
