# Generated by Django 3.2 on 2021-07-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_auto_20210724_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemtestcasemodel',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
    ]
